# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/API.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protobuf/API.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import A2L_pb2 as protobuf_dot_A2L__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protobuf/API.proto\x1a\x12protobuf/A2L.proto\"!\n\x12TreeFromA2LRequest\x12\x0b\n\x03\x61\x32l\x18\x01 \x01(\x0c\"8\n\x0b\x41\x32LResponse\x12\x0b\n\x03\x61\x32l\x18\x01 \x01(\x0c\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\"\xa5\x01\n\x13JSONFromTreeRequest\x12\x0c\n\x04tree\x18\x01 \x01(\x0c\x12\x13\n\x06indent\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x1a\n\rallow_partial\x18\x04 \x01(\x08H\x01\x88\x01\x01\x12\x1d\n\x10\x65mit_unpopulated\x18\x05 \x01(\x08H\x02\x88\x01\x01\x42\t\n\x07_indentB\x10\n\x0e_allow_partialB\x13\n\x11_emit_unpopulated\"b\n\x12\x41\x32LFromTreeRequest\x12\x0c\n\x04tree\x18\x01 \x01(\x0c\x12\x13\n\x06indent\x18\x02 \x01(\rH\x00\x88\x01\x01\x12\x13\n\x06sorted\x18\x03 \x01(\x08H\x01\x88\x01\x01\x42\t\n\x07_indentB\t\n\x07_sorted\"I\n\x0cTreeResponse\x12\x1b\n\x13serializedTreeChunk\x18\x01 \x01(\x0c\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\"Q\n\x13TreeFromJSONRequest\x12\x0c\n\x04json\x18\x01 \x01(\x0c\x12\x1a\n\rallow_partial\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\x10\n\x0e_allow_partial\":\n\x0cJSONResponse\x12\x0c\n\x04json\x18\x01 \x01(\x0c\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error2\xf8\x01\n\x03\x41\x32L\x12:\n\x0eGetTreeFromA2L\x12\x13.TreeFromA2LRequest\x1a\r.TreeResponse\"\x00(\x01\x30\x01\x12<\n\x0fGetJSONFromTree\x12\x14.JSONFromTreeRequest\x1a\r.JSONResponse\"\x00(\x01\x30\x01\x12<\n\x0fGetTreeFromJSON\x12\x14.TreeFromJSONRequest\x1a\r.TreeResponse\"\x00(\x01\x30\x01\x12\x39\n\x0eGetA2LFromTree\x12\x13.A2LFromTreeRequest\x1a\x0c.A2LResponse\"\x00(\x01\x30\x01\x42\x0eZ\x0c./../pkg/a2lb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.API_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./../pkg/a2l'
  _globals['_TREEFROMA2LREQUEST']._serialized_start=42
  _globals['_TREEFROMA2LREQUEST']._serialized_end=75
  _globals['_A2LRESPONSE']._serialized_start=77
  _globals['_A2LRESPONSE']._serialized_end=133
  _globals['_JSONFROMTREEREQUEST']._serialized_start=136
  _globals['_JSONFROMTREEREQUEST']._serialized_end=301
  _globals['_A2LFROMTREEREQUEST']._serialized_start=303
  _globals['_A2LFROMTREEREQUEST']._serialized_end=401
  _globals['_TREERESPONSE']._serialized_start=403
  _globals['_TREERESPONSE']._serialized_end=476
  _globals['_TREEFROMJSONREQUEST']._serialized_start=478
  _globals['_TREEFROMJSONREQUEST']._serialized_end=559
  _globals['_JSONRESPONSE']._serialized_start=561
  _globals['_JSONRESPONSE']._serialized_end=619
  _globals['_A2L']._serialized_start=622
  _globals['_A2L']._serialized_end=870
# @@protoc_insertion_point(module_scope)
