# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protobuf import API_pb2 as protobuf_dot_API__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobuf/API_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class A2LStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTreeFromA2L = channel.stream_stream(
                '/A2L/GetTreeFromA2L',
                request_serializer=protobuf_dot_API__pb2.TreeFromA2LRequest.SerializeToString,
                response_deserializer=protobuf_dot_API__pb2.TreeResponse.FromString,
                _registered_method=True)
        self.GetJSONFromTree = channel.stream_stream(
                '/A2L/GetJSONFromTree',
                request_serializer=protobuf_dot_API__pb2.JSONFromTreeRequest.SerializeToString,
                response_deserializer=protobuf_dot_API__pb2.JSONResponse.FromString,
                _registered_method=True)
        self.GetTreeFromJSON = channel.stream_stream(
                '/A2L/GetTreeFromJSON',
                request_serializer=protobuf_dot_API__pb2.TreeFromJSONRequest.SerializeToString,
                response_deserializer=protobuf_dot_API__pb2.TreeResponse.FromString,
                _registered_method=True)
        self.GetA2LFromTree = channel.stream_stream(
                '/A2L/GetA2LFromTree',
                request_serializer=protobuf_dot_API__pb2.A2LFromTreeRequest.SerializeToString,
                response_deserializer=protobuf_dot_API__pb2.A2LResponse.FromString,
                _registered_method=True)


class A2LServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTreeFromA2L(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJSONFromTree(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTreeFromJSON(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetA2LFromTree(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A2LServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTreeFromA2L': grpc.stream_stream_rpc_method_handler(
                    servicer.GetTreeFromA2L,
                    request_deserializer=protobuf_dot_API__pb2.TreeFromA2LRequest.FromString,
                    response_serializer=protobuf_dot_API__pb2.TreeResponse.SerializeToString,
            ),
            'GetJSONFromTree': grpc.stream_stream_rpc_method_handler(
                    servicer.GetJSONFromTree,
                    request_deserializer=protobuf_dot_API__pb2.JSONFromTreeRequest.FromString,
                    response_serializer=protobuf_dot_API__pb2.JSONResponse.SerializeToString,
            ),
            'GetTreeFromJSON': grpc.stream_stream_rpc_method_handler(
                    servicer.GetTreeFromJSON,
                    request_deserializer=protobuf_dot_API__pb2.TreeFromJSONRequest.FromString,
                    response_serializer=protobuf_dot_API__pb2.TreeResponse.SerializeToString,
            ),
            'GetA2LFromTree': grpc.stream_stream_rpc_method_handler(
                    servicer.GetA2LFromTree,
                    request_deserializer=protobuf_dot_API__pb2.A2LFromTreeRequest.FromString,
                    response_serializer=protobuf_dot_API__pb2.A2LResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'A2L', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('A2L', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class A2L(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTreeFromA2L(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/A2L/GetTreeFromA2L',
            protobuf_dot_API__pb2.TreeFromA2LRequest.SerializeToString,
            protobuf_dot_API__pb2.TreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJSONFromTree(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/A2L/GetJSONFromTree',
            protobuf_dot_API__pb2.JSONFromTreeRequest.SerializeToString,
            protobuf_dot_API__pb2.JSONResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTreeFromJSON(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/A2L/GetTreeFromJSON',
            protobuf_dot_API__pb2.TreeFromJSONRequest.SerializeToString,
            protobuf_dot_API__pb2.TreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetA2LFromTree(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/A2L/GetA2LFromTree',
            protobuf_dot_API__pb2.A2LFromTreeRequest.SerializeToString,
            protobuf_dot_API__pb2.A2LResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
