# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/IF_DATA.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protobuf/IF_DATA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import shared_pb2 as protobuf_dot_shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protobuf/IF_DATA.proto\x1a\x15protobuf/shared.proto\"W\n\nIfDataType\x12\x1e\n\x04Name\x18\x01 \x01(\x0b\x32\n.IdentTypeR\x04Name\x12)\n\x04\x42lob\x18\x02 \x03(\x0b\x32\x15.GenericParameterTypeR\x04\x42lob\"\x85\x02\n\x14GenericParameterType\x12\x1c\n\x03Tag\x18\x01 \x01(\x0b\x32\x08.TagTypeH\x00R\x03Tag\x12%\n\x06String\x18\x02 \x01(\x0b\x32\x0b.StringTypeH\x00R\x06String\x12\x1f\n\x04Long\x18\x03 \x01(\x0b\x32\t.LongTypeH\x00R\x04Long\x12\"\n\x05\x46loat\x18\x04 \x01(\x0b\x32\n.FloatTypeH\x00R\x05\x46loat\x12,\n\x07Generic\x18\x05 \x01(\x0b\x32\x10.GenericNodeTypeH\x00R\x07Generic\x12,\n\nIdentifier\x18\x06 \x01(\x0b\x32\n.IdentTypeH\x00R\nIdentifierB\x07\n\x05oneof\"b\n\x0fGenericNodeType\x12\x1e\n\x04Name\x18\x01 \x01(\x0b\x32\n.IdentTypeR\x04Name\x12/\n\x07\x45lement\x18\x02 \x03(\x0b\x32\x15.GenericParameterTypeR\x07\x45lementB\x0eZ\x0c./../pkg/a2lb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.IF_DATA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./../pkg/a2l'
  _globals['_IFDATATYPE']._serialized_start=49
  _globals['_IFDATATYPE']._serialized_end=136
  _globals['_GENERICPARAMETERTYPE']._serialized_start=139
  _globals['_GENERICPARAMETERTYPE']._serialized_end=400
  _globals['_GENERICNODETYPE']._serialized_start=402
  _globals['_GENERICNODETYPE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
