# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/shared.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protobuf/shared.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protobuf/shared.proto\"4\n\x07IntType\x12\r\n\x05Value\x18\x01 \x01(\x05\x12\x0c\n\x04\x42\x61se\x18\x02 \x01(\r\x12\x0c\n\x04Size\x18\x03 \x01(\r\"5\n\x08LongType\x12\r\n\x05Value\x18\x01 \x01(\x03\x12\x0c\n\x04\x42\x61se\x18\x02 \x01(\r\x12\x0c\n\x04Size\x18\x03 \x01(\r\"\xb3\x01\n\tFloatType\x12\r\n\x05Value\x18\x01 \x01(\x01\x12\x19\n\x0cIntegralSign\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x0cIntegralSize\x18\x03 \x01(\r\x12\x13\n\x0b\x44\x65\x63imalSize\x18\x04 \x01(\r\x12\x19\n\x0c\x45xponentSign\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x0c\x45xponentSize\x18\x06 \x01(\rB\x0f\n\r_IntegralSignB\x0f\n\r_ExponentSign\"\x1a\n\tIdentType\x12\r\n\x05Value\x18\x01 \x01(\t\"\x1b\n\nStringType\x12\r\n\x05Value\x18\x01 \x01(\t\"\x18\n\x07TagType\x12\r\n\x05Value\x18\x01 \x01(\tB\x0eZ\x0c./../pkg/a2lb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.shared_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./../pkg/a2l'
  _globals['_INTTYPE']._serialized_start=25
  _globals['_INTTYPE']._serialized_end=77
  _globals['_LONGTYPE']._serialized_start=79
  _globals['_LONGTYPE']._serialized_end=132
  _globals['_FLOATTYPE']._serialized_start=135
  _globals['_FLOATTYPE']._serialized_end=314
  _globals['_IDENTTYPE']._serialized_start=316
  _globals['_IDENTTYPE']._serialized_end=342
  _globals['_STRINGTYPE']._serialized_start=344
  _globals['_STRINGTYPE']._serialized_end=371
  _globals['_TAGTYPE']._serialized_start=373
  _globals['_TAGTYPE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
