// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: protobufs/A2ML.proto

package a2l

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Declaration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Oneof:
	//	*Declaration_TypeDefinition
	//	*Declaration_BlockDefinition
	Oneof isDeclaration_Oneof `protobuf_oneof:"oneof"`
}

func (x *Declaration) Reset() {
	*x = Declaration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Declaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Declaration) ProtoMessage() {}

func (x *Declaration) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Declaration.ProtoReflect.Descriptor instead.
func (*Declaration) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{0}
}

func (m *Declaration) GetOneof() isDeclaration_Oneof {
	if m != nil {
		return m.Oneof
	}
	return nil
}

func (x *Declaration) GetTypeDefinition() *TypeDefinition {
	if x, ok := x.GetOneof().(*Declaration_TypeDefinition); ok {
		return x.TypeDefinition
	}
	return nil
}

func (x *Declaration) GetBlockDefinition() *BlockDefinition {
	if x, ok := x.GetOneof().(*Declaration_BlockDefinition); ok {
		return x.BlockDefinition
	}
	return nil
}

type isDeclaration_Oneof interface {
	isDeclaration_Oneof()
}

type Declaration_TypeDefinition struct {
	TypeDefinition *TypeDefinition `protobuf:"bytes,1,opt,name=type_definition,proto3,oneof"`
}

type Declaration_BlockDefinition struct {
	BlockDefinition *BlockDefinition `protobuf:"bytes,2,opt,name=block_definition,proto3,oneof"`
}

func (*Declaration_TypeDefinition) isDeclaration_Oneof() {}

func (*Declaration_BlockDefinition) isDeclaration_Oneof() {}

type TypeDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeName *TypeName `protobuf:"bytes,1,opt,name=type_name,proto3" json:"type_name,omitempty"`
}

func (x *TypeDefinition) Reset() {
	*x = TypeDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDefinition) ProtoMessage() {}

func (x *TypeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDefinition.ProtoReflect.Descriptor instead.
func (*TypeDefinition) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{1}
}

func (x *TypeDefinition) GetTypeName() *TypeName {
	if x != nil {
		return x.TypeName
	}
	return nil
}

type TypeName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Oneof:
	//	*TypeName_PredefinedTypeName
	//	*TypeName_StructTypeName
	//	*TypeName_TaggedstructTypeName
	//	*TypeName_TaggedunionTypeName
	//	*TypeName_EnumTypeName
	Oneof isTypeName_Oneof `protobuf_oneof:"oneof"`
}

func (x *TypeName) Reset() {
	*x = TypeName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeName) ProtoMessage() {}

func (x *TypeName) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeName.ProtoReflect.Descriptor instead.
func (*TypeName) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{2}
}

func (m *TypeName) GetOneof() isTypeName_Oneof {
	if m != nil {
		return m.Oneof
	}
	return nil
}

func (x *TypeName) GetPredefinedTypeName() *PredefinedTypeName {
	if x, ok := x.GetOneof().(*TypeName_PredefinedTypeName); ok {
		return x.PredefinedTypeName
	}
	return nil
}

func (x *TypeName) GetStructTypeName() *StructTypeName {
	if x, ok := x.GetOneof().(*TypeName_StructTypeName); ok {
		return x.StructTypeName
	}
	return nil
}

func (x *TypeName) GetTaggedstructTypeName() *TaggedstructTypeName {
	if x, ok := x.GetOneof().(*TypeName_TaggedstructTypeName); ok {
		return x.TaggedstructTypeName
	}
	return nil
}

func (x *TypeName) GetTaggedunionTypeName() *TaggedunionTypeName {
	if x, ok := x.GetOneof().(*TypeName_TaggedunionTypeName); ok {
		return x.TaggedunionTypeName
	}
	return nil
}

func (x *TypeName) GetEnumTypeName() *EnumTypeName {
	if x, ok := x.GetOneof().(*TypeName_EnumTypeName); ok {
		return x.EnumTypeName
	}
	return nil
}

type isTypeName_Oneof interface {
	isTypeName_Oneof()
}

type TypeName_PredefinedTypeName struct {
	PredefinedTypeName *PredefinedTypeName `protobuf:"bytes,1,opt,name=predefined_type_name,proto3,oneof"`
}

type TypeName_StructTypeName struct {
	StructTypeName *StructTypeName `protobuf:"bytes,2,opt,name=struct_type_name,proto3,oneof"`
}

type TypeName_TaggedstructTypeName struct {
	TaggedstructTypeName *TaggedstructTypeName `protobuf:"bytes,3,opt,name=taggedstruct_type_name,proto3,oneof"`
}

type TypeName_TaggedunionTypeName struct {
	TaggedunionTypeName *TaggedunionTypeName `protobuf:"bytes,4,opt,name=taggedunion_type_name,proto3,oneof"`
}

type TypeName_EnumTypeName struct {
	EnumTypeName *EnumTypeName `protobuf:"bytes,5,opt,name=enum_type_name,proto3,oneof"`
}

func (*TypeName_PredefinedTypeName) isTypeName_Oneof() {}

func (*TypeName_StructTypeName) isTypeName_Oneof() {}

func (*TypeName_TaggedstructTypeName) isTypeName_Oneof() {}

func (*TypeName_TaggedunionTypeName) isTypeName_Oneof() {}

func (*TypeName_EnumTypeName) isTypeName_Oneof() {}

type PredefinedTypeName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PredefinedTypeName) Reset() {
	*x = PredefinedTypeName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredefinedTypeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredefinedTypeName) ProtoMessage() {}

func (x *PredefinedTypeName) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredefinedTypeName.ProtoReflect.Descriptor instead.
func (*PredefinedTypeName) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{3}
}

func (x *PredefinedTypeName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BlockDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag *TagType `protobuf:"bytes,1,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	// Types that are assignable to Oneof:
	//	*BlockDefinition_TypeName
	//	*BlockDefinition_Member
	Oneof isBlockDefinition_Oneof `protobuf_oneof:"oneof"`
}

func (x *BlockDefinition) Reset() {
	*x = BlockDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDefinition) ProtoMessage() {}

func (x *BlockDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDefinition.ProtoReflect.Descriptor instead.
func (*BlockDefinition) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{4}
}

func (x *BlockDefinition) GetTag() *TagType {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (m *BlockDefinition) GetOneof() isBlockDefinition_Oneof {
	if m != nil {
		return m.Oneof
	}
	return nil
}

func (x *BlockDefinition) GetTypeName() *TypeName {
	if x, ok := x.GetOneof().(*BlockDefinition_TypeName); ok {
		return x.TypeName
	}
	return nil
}

func (x *BlockDefinition) GetMember() *Member {
	if x, ok := x.GetOneof().(*BlockDefinition_Member); ok {
		return x.Member
	}
	return nil
}

type isBlockDefinition_Oneof interface {
	isBlockDefinition_Oneof()
}

type BlockDefinition_TypeName struct {
	TypeName *TypeName `protobuf:"bytes,2,opt,name=type_name,proto3,oneof"`
}

type BlockDefinition_Member struct {
	Member *Member `protobuf:"bytes,3,opt,name=member,proto3,oneof"` // This is not part of the specification. However, Canape generates A2L with this format...
}

func (*BlockDefinition_TypeName) isBlockDefinition_Oneof() {}

func (*BlockDefinition_Member) isBlockDefinition_Oneof() {}

type EnumTypeName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier     *IdentType    `protobuf:"bytes,1,opt,name=identifier,proto3,oneof" json:"identifier,omitempty"`
	EnumeratorList []*Enumerator `protobuf:"bytes,2,rep,name=enumerator_list,proto3" json:"enumerator_list,omitempty"`
}

func (x *EnumTypeName) Reset() {
	*x = EnumTypeName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumTypeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumTypeName) ProtoMessage() {}

func (x *EnumTypeName) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumTypeName.ProtoReflect.Descriptor instead.
func (*EnumTypeName) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{5}
}

func (x *EnumTypeName) GetIdentifier() *IdentType {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *EnumTypeName) GetEnumeratorList() []*Enumerator {
	if x != nil {
		return x.EnumeratorList
	}
	return nil
}

type Enumerator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword  string    `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Constant *LongType `protobuf:"bytes,2,opt,name=constant,proto3" json:"constant,omitempty"`
}

func (x *Enumerator) Reset() {
	*x = Enumerator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enumerator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enumerator) ProtoMessage() {}

func (x *Enumerator) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enumerator.ProtoReflect.Descriptor instead.
func (*Enumerator) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{6}
}

func (x *Enumerator) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *Enumerator) GetConstant() *LongType {
	if x != nil {
		return x.Constant
	}
	return nil
}

type StructTypeName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier       *IdentType      `protobuf:"bytes,1,opt,name=identifier,proto3,oneof" json:"identifier,omitempty"`
	StructMemberList []*StructMember `protobuf:"bytes,2,rep,name=struct_member_list,proto3" json:"struct_member_list,omitempty"`
}

func (x *StructTypeName) Reset() {
	*x = StructTypeName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructTypeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructTypeName) ProtoMessage() {}

func (x *StructTypeName) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructTypeName.ProtoReflect.Descriptor instead.
func (*StructTypeName) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{7}
}

func (x *StructTypeName) GetIdentifier() *IdentType {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *StructTypeName) GetStructMemberList() []*StructMember {
	if x != nil {
		return x.StructMemberList
	}
	return nil
}

type StructMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member *Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	Star   bool    `protobuf:"varint,2,opt,name=star,proto3" json:"star,omitempty"`
}

func (x *StructMember) Reset() {
	*x = StructMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructMember) ProtoMessage() {}

func (x *StructMember) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructMember.ProtoReflect.Descriptor instead.
func (*StructMember) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{8}
}

func (x *StructMember) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *StructMember) GetStar() bool {
	if x != nil {
		return x.Star
	}
	return false
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeName       *TypeName       `protobuf:"bytes,1,opt,name=type_name,proto3" json:"type_name,omitempty"`
	ArraySpecifier *ArraySpecifier `protobuf:"bytes,2,opt,name=array_specifier,proto3,oneof" json:"array_specifier,omitempty"`
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{9}
}

func (x *Member) GetTypeName() *TypeName {
	if x != nil {
		return x.TypeName
	}
	return nil
}

func (x *Member) GetArraySpecifier() *ArraySpecifier {
	if x != nil {
		return x.ArraySpecifier
	}
	return nil
}

type ArraySpecifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constant []*LongType `protobuf:"bytes,1,rep,name=constant,proto3" json:"constant,omitempty"`
}

func (x *ArraySpecifier) Reset() {
	*x = ArraySpecifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArraySpecifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArraySpecifier) ProtoMessage() {}

func (x *ArraySpecifier) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArraySpecifier.ProtoReflect.Descriptor instead.
func (*ArraySpecifier) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{10}
}

func (x *ArraySpecifier) GetConstant() []*LongType {
	if x != nil {
		return x.Constant
	}
	return nil
}

type TaggedstructTypeName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier             *IdentType            `protobuf:"bytes,1,opt,name=identifier,proto3,oneof" json:"identifier,omitempty"`
	TaggedstructMemberList []*TaggedstructMember `protobuf:"bytes,2,rep,name=taggedstruct_member_list,proto3" json:"taggedstruct_member_list,omitempty"`
}

func (x *TaggedstructTypeName) Reset() {
	*x = TaggedstructTypeName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaggedstructTypeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedstructTypeName) ProtoMessage() {}

func (x *TaggedstructTypeName) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedstructTypeName.ProtoReflect.Descriptor instead.
func (*TaggedstructTypeName) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{11}
}

func (x *TaggedstructTypeName) GetIdentifier() *IdentType {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *TaggedstructTypeName) GetTaggedstructMemberList() []*TaggedstructMember {
	if x != nil {
		return x.TaggedstructMemberList
	}
	return nil
}

type TaggedstructMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Oneof:
	//	*TaggedstructMember_TaggedstructDefinition
	//	*TaggedstructMember_BlockDefinition
	Oneof isTaggedstructMember_Oneof `protobuf_oneof:"oneof"`
	Star  bool                       `protobuf:"varint,3,opt,name=star,proto3" json:"star,omitempty"`
}

func (x *TaggedstructMember) Reset() {
	*x = TaggedstructMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaggedstructMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedstructMember) ProtoMessage() {}

func (x *TaggedstructMember) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedstructMember.ProtoReflect.Descriptor instead.
func (*TaggedstructMember) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{12}
}

func (m *TaggedstructMember) GetOneof() isTaggedstructMember_Oneof {
	if m != nil {
		return m.Oneof
	}
	return nil
}

func (x *TaggedstructMember) GetTaggedstructDefinition() *TaggedstructDefinition {
	if x, ok := x.GetOneof().(*TaggedstructMember_TaggedstructDefinition); ok {
		return x.TaggedstructDefinition
	}
	return nil
}

func (x *TaggedstructMember) GetBlockDefinition() *BlockDefinition {
	if x, ok := x.GetOneof().(*TaggedstructMember_BlockDefinition); ok {
		return x.BlockDefinition
	}
	return nil
}

func (x *TaggedstructMember) GetStar() bool {
	if x != nil {
		return x.Star
	}
	return false
}

type isTaggedstructMember_Oneof interface {
	isTaggedstructMember_Oneof()
}

type TaggedstructMember_TaggedstructDefinition struct {
	TaggedstructDefinition *TaggedstructDefinition `protobuf:"bytes,1,opt,name=taggedstruct_definition,proto3,oneof"`
}

type TaggedstructMember_BlockDefinition struct {
	BlockDefinition *BlockDefinition `protobuf:"bytes,2,opt,name=block_definition,proto3,oneof"`
}

func (*TaggedstructMember_TaggedstructDefinition) isTaggedstructMember_Oneof() {}

func (*TaggedstructMember_BlockDefinition) isTaggedstructMember_Oneof() {}

type TaggedstructDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag    *TagType `protobuf:"bytes,1,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	Member *Member  `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	Star   bool     `protobuf:"varint,3,opt,name=star,proto3" json:"star,omitempty"`
}

func (x *TaggedstructDefinition) Reset() {
	*x = TaggedstructDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaggedstructDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedstructDefinition) ProtoMessage() {}

func (x *TaggedstructDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedstructDefinition.ProtoReflect.Descriptor instead.
func (*TaggedstructDefinition) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{13}
}

func (x *TaggedstructDefinition) GetTag() *TagType {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *TaggedstructDefinition) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *TaggedstructDefinition) GetStar() bool {
	if x != nil {
		return x.Star
	}
	return false
}

type TaggedunionTypeName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier            *IdentType           `protobuf:"bytes,1,opt,name=identifier,proto3,oneof" json:"identifier,omitempty"`
	TaggedunionMemberList []*TaggedunionMember `protobuf:"bytes,2,rep,name=taggedunion_member_list,proto3" json:"taggedunion_member_list,omitempty"`
}

func (x *TaggedunionTypeName) Reset() {
	*x = TaggedunionTypeName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaggedunionTypeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedunionTypeName) ProtoMessage() {}

func (x *TaggedunionTypeName) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedunionTypeName.ProtoReflect.Descriptor instead.
func (*TaggedunionTypeName) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{14}
}

func (x *TaggedunionTypeName) GetIdentifier() *IdentType {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *TaggedunionTypeName) GetTaggedunionMemberList() []*TaggedunionMember {
	if x != nil {
		return x.TaggedunionMemberList
	}
	return nil
}

type TaggedunionMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Oneof:
	//	*TaggedunionMember_TagMember
	//	*TaggedunionMember_BlockDefinition
	Oneof isTaggedunionMember_Oneof `protobuf_oneof:"oneof"`
}

func (x *TaggedunionMember) Reset() {
	*x = TaggedunionMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaggedunionMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedunionMember) ProtoMessage() {}

func (x *TaggedunionMember) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedunionMember.ProtoReflect.Descriptor instead.
func (*TaggedunionMember) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{15}
}

func (m *TaggedunionMember) GetOneof() isTaggedunionMember_Oneof {
	if m != nil {
		return m.Oneof
	}
	return nil
}

func (x *TaggedunionMember) GetTagMember() *TagMember {
	if x, ok := x.GetOneof().(*TaggedunionMember_TagMember); ok {
		return x.TagMember
	}
	return nil
}

func (x *TaggedunionMember) GetBlockDefinition() *BlockDefinition {
	if x, ok := x.GetOneof().(*TaggedunionMember_BlockDefinition); ok {
		return x.BlockDefinition
	}
	return nil
}

type isTaggedunionMember_Oneof interface {
	isTaggedunionMember_Oneof()
}

type TaggedunionMember_TagMember struct {
	TagMember *TagMember `protobuf:"bytes,1,opt,name=tag_member,proto3,oneof"`
}

type TaggedunionMember_BlockDefinition struct {
	BlockDefinition *BlockDefinition `protobuf:"bytes,2,opt,name=block_definition,proto3,oneof"`
}

func (*TaggedunionMember_TagMember) isTaggedunionMember_Oneof() {}

func (*TaggedunionMember_BlockDefinition) isTaggedunionMember_Oneof() {}

// not part of the specification...
type TagMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag    *TagType `protobuf:"bytes,1,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	Member *Member  `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *TagMember) Reset() {
	*x = TagMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_A2ML_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagMember) ProtoMessage() {}

func (x *TagMember) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_A2ML_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagMember.ProtoReflect.Descriptor instead.
func (*TagMember) Descriptor() ([]byte, []int) {
	return file_protobufs_A2ML_proto_rawDescGZIP(), []int{16}
}

func (x *TagMember) GetTag() *TagType {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *TagMember) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

var File_protobufs_A2ML_proto protoreflect.FileDescriptor

var file_protobufs_A2ML_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x41, 0x32, 0x4d, 0x4c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95,
	0x01, 0x0a, 0x0b, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c,
	0x0a, 0x0f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0f, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x10,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x10, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x07, 0x0a,
	0x05, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x3b, 0x0a, 0x0f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x09, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x80, 0x03, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x4b, 0x0a, 0x14, 0x70, 0x72, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x70, 0x72, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x14, 0x70, 0x72, 0x65, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3f,
	0x0a, 0x10, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x10, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x51, 0x0a, 0x16, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x16, 0x74, 0x61, 0x67, 0x67,
	0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x4e, 0x0a, 0x15, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x75, 0x6e, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x15, 0x74, 0x61, 0x67,
	0x67, 0x65, 0x64, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x6e, 0x75,
	0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x65,
	0x6e, 0x75, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x07, 0x0a,
	0x05, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x2a, 0x0a, 0x14, 0x70, 0x72, 0x65, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x10, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x48, 0x01,
	0x52, 0x03, 0x74, 0x61, 0x67, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x6f, 0x6e, 0x65, 0x6f, 0x66,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x74, 0x61, 0x67, 0x22, 0x87, 0x01, 0x0a, 0x0e, 0x65, 0x6e, 0x75,
	0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x35, 0x0a, 0x0f,
	0x65, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x0f, 0x65, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x22, 0x4d, 0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x25, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4c,
	0x6f, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x74, 0x22, 0x92, 0x01, 0x0a, 0x10, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x3e, 0x0a, 0x12, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x12, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x0d, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x74, 0x61, 0x72, 0x22, 0x87, 0x01, 0x0a,
	0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x3f, 0x0a, 0x0f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x72, 0x72,
	0x61, 0x79, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0f,
	0x61, 0x72, 0x72, 0x61, 0x79, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x88,
	0x01, 0x01, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x5f, 0x73, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x0f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x5f,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x08, 0x63, 0x6f, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4c, 0x6f,
	0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74,
	0x22, 0xaa, 0x01, 0x0a, 0x16, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x50, 0x0a, 0x18,
	0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x18, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x0d,
	0x0a, 0x0b, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0xc9, 0x01,
	0x0a, 0x13, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x54, 0x0a, 0x17, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x17, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x10, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x10, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x74, 0x61, 0x72,
	0x42, 0x07, 0x0a, 0x05, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x77, 0x0a, 0x17, 0x74, 0x61, 0x67,
	0x67, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x03, 0x74,
	0x61, 0x67, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x74, 0x61, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x74,
	0x61, 0x67, 0x22, 0xa6, 0x01, 0x0a, 0x15, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x0a,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0a,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x4d, 0x0a,
	0x17, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x17, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x0d, 0x0a, 0x0b,
	0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x8d, 0x01, 0x0a, 0x12,
	0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x2d, 0x0a, 0x0a, 0x74, 0x61, 0x67, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x61, 0x67, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x74, 0x61, 0x67, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x3f, 0x0a, 0x10, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00,
	0x52, 0x10, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x56, 0x0a, 0x0a, 0x74,
	0x61, 0x67, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x03, 0x74, 0x61, 0x67, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x06, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x5f,
	0x74, 0x61, 0x67, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x61, 0x32, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufs_A2ML_proto_rawDescOnce sync.Once
	file_protobufs_A2ML_proto_rawDescData = file_protobufs_A2ML_proto_rawDesc
)

func file_protobufs_A2ML_proto_rawDescGZIP() []byte {
	file_protobufs_A2ML_proto_rawDescOnce.Do(func() {
		file_protobufs_A2ML_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_A2ML_proto_rawDescData)
	})
	return file_protobufs_A2ML_proto_rawDescData
}

var file_protobufs_A2ML_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_protobufs_A2ML_proto_goTypes = []interface{}{
	(*Declaration)(nil),            // 0: declaration
	(*TypeDefinition)(nil),         // 1: type_definition
	(*TypeName)(nil),               // 2: type_name
	(*PredefinedTypeName)(nil),     // 3: predefined_type_name
	(*BlockDefinition)(nil),        // 4: block_definition
	(*EnumTypeName)(nil),           // 5: enum_type_name
	(*Enumerator)(nil),             // 6: enumerator
	(*StructTypeName)(nil),         // 7: struct_type_name
	(*StructMember)(nil),           // 8: struct_member
	(*Member)(nil),                 // 9: member
	(*ArraySpecifier)(nil),         // 10: array_specifier
	(*TaggedstructTypeName)(nil),   // 11: taggedstruct_type_name
	(*TaggedstructMember)(nil),     // 12: taggedstruct_member
	(*TaggedstructDefinition)(nil), // 13: taggedstruct_definition
	(*TaggedunionTypeName)(nil),    // 14: taggedunion_type_name
	(*TaggedunionMember)(nil),      // 15: taggedunion_member
	(*TagMember)(nil),              // 16: tag_member
	(*TagType)(nil),                // 17: TagType
	(*IdentType)(nil),              // 18: IdentType
	(*LongType)(nil),               // 19: LongType
}
var file_protobufs_A2ML_proto_depIdxs = []int32{
	1,  // 0: declaration.type_definition:type_name -> type_definition
	4,  // 1: declaration.block_definition:type_name -> block_definition
	2,  // 2: type_definition.type_name:type_name -> type_name
	3,  // 3: type_name.predefined_type_name:type_name -> predefined_type_name
	7,  // 4: type_name.struct_type_name:type_name -> struct_type_name
	11, // 5: type_name.taggedstruct_type_name:type_name -> taggedstruct_type_name
	14, // 6: type_name.taggedunion_type_name:type_name -> taggedunion_type_name
	5,  // 7: type_name.enum_type_name:type_name -> enum_type_name
	17, // 8: block_definition.tag:type_name -> TagType
	2,  // 9: block_definition.type_name:type_name -> type_name
	9,  // 10: block_definition.member:type_name -> member
	18, // 11: enum_type_name.identifier:type_name -> IdentType
	6,  // 12: enum_type_name.enumerator_list:type_name -> enumerator
	19, // 13: enumerator.constant:type_name -> LongType
	18, // 14: struct_type_name.identifier:type_name -> IdentType
	8,  // 15: struct_type_name.struct_member_list:type_name -> struct_member
	9,  // 16: struct_member.member:type_name -> member
	2,  // 17: member.type_name:type_name -> type_name
	10, // 18: member.array_specifier:type_name -> array_specifier
	19, // 19: array_specifier.constant:type_name -> LongType
	18, // 20: taggedstruct_type_name.identifier:type_name -> IdentType
	12, // 21: taggedstruct_type_name.taggedstruct_member_list:type_name -> taggedstruct_member
	13, // 22: taggedstruct_member.taggedstruct_definition:type_name -> taggedstruct_definition
	4,  // 23: taggedstruct_member.block_definition:type_name -> block_definition
	17, // 24: taggedstruct_definition.tag:type_name -> TagType
	9,  // 25: taggedstruct_definition.member:type_name -> member
	18, // 26: taggedunion_type_name.identifier:type_name -> IdentType
	15, // 27: taggedunion_type_name.taggedunion_member_list:type_name -> taggedunion_member
	16, // 28: taggedunion_member.tag_member:type_name -> tag_member
	4,  // 29: taggedunion_member.block_definition:type_name -> block_definition
	17, // 30: tag_member.tag:type_name -> TagType
	9,  // 31: tag_member.member:type_name -> member
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_protobufs_A2ML_proto_init() }
func file_protobufs_A2ML_proto_init() {
	if File_protobufs_A2ML_proto != nil {
		return
	}
	file_protobufs_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protobufs_A2ML_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Declaration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredefinedTypeName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumTypeName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enumerator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructTypeName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArraySpecifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaggedstructTypeName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaggedstructMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaggedstructDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaggedunionTypeName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaggedunionMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_A2ML_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobufs_A2ML_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Declaration_TypeDefinition)(nil),
		(*Declaration_BlockDefinition)(nil),
	}
	file_protobufs_A2ML_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*TypeName_PredefinedTypeName)(nil),
		(*TypeName_StructTypeName)(nil),
		(*TypeName_TaggedstructTypeName)(nil),
		(*TypeName_TaggedunionTypeName)(nil),
		(*TypeName_EnumTypeName)(nil),
	}
	file_protobufs_A2ML_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*BlockDefinition_TypeName)(nil),
		(*BlockDefinition_Member)(nil),
	}
	file_protobufs_A2ML_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_protobufs_A2ML_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_protobufs_A2ML_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_protobufs_A2ML_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_protobufs_A2ML_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*TaggedstructMember_TaggedstructDefinition)(nil),
		(*TaggedstructMember_BlockDefinition)(nil),
	}
	file_protobufs_A2ML_proto_msgTypes[13].OneofWrappers = []interface{}{}
	file_protobufs_A2ML_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_protobufs_A2ML_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*TaggedunionMember_TagMember)(nil),
		(*TaggedunionMember_BlockDefinition)(nil),
	}
	file_protobufs_A2ML_proto_msgTypes[16].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_A2ML_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobufs_A2ML_proto_goTypes,
		DependencyIndexes: file_protobufs_A2ML_proto_depIdxs,
		MessageInfos:      file_protobufs_A2ML_proto_msgTypes,
	}.Build()
	File_protobufs_A2ML_proto = out.File
	file_protobufs_A2ML_proto_rawDesc = nil
	file_protobufs_A2ML_proto_goTypes = nil
	file_protobufs_A2ML_proto_depIdxs = nil
}
