// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: protobufs/IF_DATA.proto

package a2l

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IfDataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *IdentType              `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Blob []*GenericParameterType `protobuf:"bytes,2,rep,name=Blob,proto3" json:"Blob,omitempty"`
}

func (x *IfDataType) Reset() {
	*x = IfDataType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_IF_DATA_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfDataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfDataType) ProtoMessage() {}

func (x *IfDataType) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_IF_DATA_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfDataType.ProtoReflect.Descriptor instead.
func (*IfDataType) Descriptor() ([]byte, []int) {
	return file_protobufs_IF_DATA_proto_rawDescGZIP(), []int{0}
}

func (x *IfDataType) GetName() *IdentType {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *IfDataType) GetBlob() []*GenericParameterType {
	if x != nil {
		return x.Blob
	}
	return nil
}

type GenericParameterType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Oneof:
	//	*GenericParameterType_Tag
	//	*GenericParameterType_String_
	//	*GenericParameterType_Long
	//	*GenericParameterType_Float
	//	*GenericParameterType_Generic
	//	*GenericParameterType_Identifier
	Oneof isGenericParameterType_Oneof `protobuf_oneof:"oneof"`
}

func (x *GenericParameterType) Reset() {
	*x = GenericParameterType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_IF_DATA_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericParameterType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericParameterType) ProtoMessage() {}

func (x *GenericParameterType) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_IF_DATA_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericParameterType.ProtoReflect.Descriptor instead.
func (*GenericParameterType) Descriptor() ([]byte, []int) {
	return file_protobufs_IF_DATA_proto_rawDescGZIP(), []int{1}
}

func (m *GenericParameterType) GetOneof() isGenericParameterType_Oneof {
	if m != nil {
		return m.Oneof
	}
	return nil
}

func (x *GenericParameterType) GetTag() *TagType {
	if x, ok := x.GetOneof().(*GenericParameterType_Tag); ok {
		return x.Tag
	}
	return nil
}

func (x *GenericParameterType) GetString_() *StringType {
	if x, ok := x.GetOneof().(*GenericParameterType_String_); ok {
		return x.String_
	}
	return nil
}

func (x *GenericParameterType) GetLong() *LongType {
	if x, ok := x.GetOneof().(*GenericParameterType_Long); ok {
		return x.Long
	}
	return nil
}

func (x *GenericParameterType) GetFloat() *FloatType {
	if x, ok := x.GetOneof().(*GenericParameterType_Float); ok {
		return x.Float
	}
	return nil
}

func (x *GenericParameterType) GetGeneric() *GenericNodeType {
	if x, ok := x.GetOneof().(*GenericParameterType_Generic); ok {
		return x.Generic
	}
	return nil
}

func (x *GenericParameterType) GetIdentifier() *IdentType {
	if x, ok := x.GetOneof().(*GenericParameterType_Identifier); ok {
		return x.Identifier
	}
	return nil
}

type isGenericParameterType_Oneof interface {
	isGenericParameterType_Oneof()
}

type GenericParameterType_Tag struct {
	Tag *TagType `protobuf:"bytes,1,opt,name=Tag,proto3,oneof"`
}

type GenericParameterType_String_ struct {
	String_ *StringType `protobuf:"bytes,2,opt,name=String,proto3,oneof"`
}

type GenericParameterType_Long struct {
	Long *LongType `protobuf:"bytes,3,opt,name=Long,proto3,oneof"`
}

type GenericParameterType_Float struct {
	Float *FloatType `protobuf:"bytes,4,opt,name=Float,proto3,oneof"`
}

type GenericParameterType_Generic struct {
	Generic *GenericNodeType `protobuf:"bytes,5,opt,name=Generic,proto3,oneof"`
}

type GenericParameterType_Identifier struct {
	Identifier *IdentType `protobuf:"bytes,6,opt,name=Identifier,proto3,oneof"`
}

func (*GenericParameterType_Tag) isGenericParameterType_Oneof() {}

func (*GenericParameterType_String_) isGenericParameterType_Oneof() {}

func (*GenericParameterType_Long) isGenericParameterType_Oneof() {}

func (*GenericParameterType_Float) isGenericParameterType_Oneof() {}

func (*GenericParameterType_Generic) isGenericParameterType_Oneof() {}

func (*GenericParameterType_Identifier) isGenericParameterType_Oneof() {}

type GenericNodeType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    *IdentType              `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Element []*GenericParameterType `protobuf:"bytes,2,rep,name=Element,proto3" json:"Element,omitempty"`
}

func (x *GenericNodeType) Reset() {
	*x = GenericNodeType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_IF_DATA_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericNodeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericNodeType) ProtoMessage() {}

func (x *GenericNodeType) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_IF_DATA_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericNodeType.ProtoReflect.Descriptor instead.
func (*GenericNodeType) Descriptor() ([]byte, []int) {
	return file_protobufs_IF_DATA_proto_rawDescGZIP(), []int{2}
}

func (x *GenericNodeType) GetName() *IdentType {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *GenericNodeType) GetElement() []*GenericParameterType {
	if x != nil {
		return x.Element
	}
	return nil
}

var File_protobufs_IF_DATA_proto protoreflect.FileDescriptor

var file_protobufs_IF_DATA_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x49, 0x46, 0x5f, 0x44,
	0x41, 0x54, 0x41, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x57, 0x0a, 0x0a, 0x49, 0x66, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1e, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x29, 0x0a, 0x04, 0x42, 0x6c, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x42, 0x6c, 0x6f, 0x62, 0x22, 0x85, 0x02, 0x0a, 0x14, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x03, 0x54, 0x61,
	0x67, 0x12, 0x25, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00,
	0x52, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x04, 0x4c, 0x6f, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x48, 0x00, 0x52, 0x04, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x05, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x05, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x2c, 0x0a,
	0x07, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x07, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x12, 0x2c, 0x0a, 0x0a, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x6f, 0x6e, 0x65,
	0x6f, 0x66, 0x22, 0x62, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x4e, 0x6f, 0x64,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x61, 0x32, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufs_IF_DATA_proto_rawDescOnce sync.Once
	file_protobufs_IF_DATA_proto_rawDescData = file_protobufs_IF_DATA_proto_rawDesc
)

func file_protobufs_IF_DATA_proto_rawDescGZIP() []byte {
	file_protobufs_IF_DATA_proto_rawDescOnce.Do(func() {
		file_protobufs_IF_DATA_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_IF_DATA_proto_rawDescData)
	})
	return file_protobufs_IF_DATA_proto_rawDescData
}

var file_protobufs_IF_DATA_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobufs_IF_DATA_proto_goTypes = []interface{}{
	(*IfDataType)(nil),           // 0: IfDataType
	(*GenericParameterType)(nil), // 1: GenericParameterType
	(*GenericNodeType)(nil),      // 2: GenericNodeType
	(*IdentType)(nil),            // 3: IdentType
	(*TagType)(nil),              // 4: TagType
	(*StringType)(nil),           // 5: StringType
	(*LongType)(nil),             // 6: LongType
	(*FloatType)(nil),            // 7: FloatType
}
var file_protobufs_IF_DATA_proto_depIdxs = []int32{
	3,  // 0: IfDataType.Name:type_name -> IdentType
	1,  // 1: IfDataType.Blob:type_name -> GenericParameterType
	4,  // 2: GenericParameterType.Tag:type_name -> TagType
	5,  // 3: GenericParameterType.String:type_name -> StringType
	6,  // 4: GenericParameterType.Long:type_name -> LongType
	7,  // 5: GenericParameterType.Float:type_name -> FloatType
	2,  // 6: GenericParameterType.Generic:type_name -> GenericNodeType
	3,  // 7: GenericParameterType.Identifier:type_name -> IdentType
	3,  // 8: GenericNodeType.Name:type_name -> IdentType
	1,  // 9: GenericNodeType.Element:type_name -> GenericParameterType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protobufs_IF_DATA_proto_init() }
func file_protobufs_IF_DATA_proto_init() {
	if File_protobufs_IF_DATA_proto != nil {
		return
	}
	file_protobufs_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protobufs_IF_DATA_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfDataType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_IF_DATA_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericParameterType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_IF_DATA_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericNodeType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobufs_IF_DATA_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GenericParameterType_Tag)(nil),
		(*GenericParameterType_String_)(nil),
		(*GenericParameterType_Long)(nil),
		(*GenericParameterType_Float)(nil),
		(*GenericParameterType_Generic)(nil),
		(*GenericParameterType_Identifier)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_IF_DATA_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobufs_IF_DATA_proto_goTypes,
		DependencyIndexes: file_protobufs_IF_DATA_proto_depIdxs,
		MessageInfos:      file_protobufs_IF_DATA_proto_msgTypes,
	}.Build()
	File_protobufs_IF_DATA_proto = out.File
	file_protobufs_IF_DATA_proto_rawDesc = nil
	file_protobufs_IF_DATA_proto_goTypes = nil
	file_protobufs_IF_DATA_proto_depIdxs = nil
}
