// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: protobufs/shared.proto

package a2l

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64  `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Base  uint32 `protobuf:"varint,2,opt,name=Base,proto3" json:"Base,omitempty"`
	Size  uint32 `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *IntType) Reset() {
	*x = IntType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_shared_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntType) ProtoMessage() {}

func (x *IntType) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_shared_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntType.ProtoReflect.Descriptor instead.
func (*IntType) Descriptor() ([]byte, []int) {
	return file_protobufs_shared_proto_rawDescGZIP(), []int{0}
}

func (x *IntType) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IntType) GetBase() uint32 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *IntType) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type LongType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64  `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Base  uint32 `protobuf:"varint,2,opt,name=Base,proto3" json:"Base,omitempty"`
	Size  uint32 `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *LongType) Reset() {
	*x = LongType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_shared_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongType) ProtoMessage() {}

func (x *LongType) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_shared_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongType.ProtoReflect.Descriptor instead.
func (*LongType) Descriptor() ([]byte, []int) {
	return file_protobufs_shared_proto_rawDescGZIP(), []int{1}
}

func (x *LongType) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *LongType) GetBase() uint32 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *LongType) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FloatType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value        float64 `protobuf:"fixed64,1,opt,name=Value,proto3" json:"Value,omitempty"`
	IntegralSign *string `protobuf:"bytes,2,opt,name=IntegralSign,proto3,oneof" json:"IntegralSign,omitempty"`
	IntegralSize uint32  `protobuf:"varint,3,opt,name=IntegralSize,proto3" json:"IntegralSize,omitempty"`
	DecimalSize  uint32  `protobuf:"varint,4,opt,name=DecimalSize,proto3" json:"DecimalSize,omitempty"`
	// uint32 FractionalSize = 4;
	ExponentSign *string `protobuf:"bytes,5,opt,name=ExponentSign,proto3,oneof" json:"ExponentSign,omitempty"`
	ExponentSize uint32  `protobuf:"varint,6,opt,name=ExponentSize,proto3" json:"ExponentSize,omitempty"`
}

func (x *FloatType) Reset() {
	*x = FloatType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_shared_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatType) ProtoMessage() {}

func (x *FloatType) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_shared_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatType.ProtoReflect.Descriptor instead.
func (*FloatType) Descriptor() ([]byte, []int) {
	return file_protobufs_shared_proto_rawDescGZIP(), []int{2}
}

func (x *FloatType) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *FloatType) GetIntegralSign() string {
	if x != nil && x.IntegralSign != nil {
		return *x.IntegralSign
	}
	return ""
}

func (x *FloatType) GetIntegralSize() uint32 {
	if x != nil {
		return x.IntegralSize
	}
	return 0
}

func (x *FloatType) GetDecimalSize() uint32 {
	if x != nil {
		return x.DecimalSize
	}
	return 0
}

func (x *FloatType) GetExponentSign() string {
	if x != nil && x.ExponentSign != nil {
		return *x.ExponentSign
	}
	return ""
}

func (x *FloatType) GetExponentSize() uint32 {
	if x != nil {
		return x.ExponentSize
	}
	return 0
}

type IdentType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *IdentType) Reset() {
	*x = IdentType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_shared_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentType) ProtoMessage() {}

func (x *IdentType) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_shared_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentType.ProtoReflect.Descriptor instead.
func (*IdentType) Descriptor() ([]byte, []int) {
	return file_protobufs_shared_proto_rawDescGZIP(), []int{3}
}

func (x *IdentType) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StringType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *StringType) Reset() {
	*x = StringType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_shared_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringType) ProtoMessage() {}

func (x *StringType) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_shared_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringType.ProtoReflect.Descriptor instead.
func (*StringType) Descriptor() ([]byte, []int) {
	return file_protobufs_shared_proto_rawDescGZIP(), []int{4}
}

func (x *StringType) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TagType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *TagType) Reset() {
	*x = TagType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_shared_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagType) ProtoMessage() {}

func (x *TagType) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_shared_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagType.ProtoReflect.Descriptor instead.
func (*TagType) Descriptor() ([]byte, []int) {
	return file_protobufs_shared_proto_rawDescGZIP(), []int{5}
}

func (x *TagType) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_protobufs_shared_proto protoreflect.FileDescriptor

var file_protobufs_shared_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x07, 0x49, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x61, 0x73,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0x48, 0x0a, 0x08, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xff, 0x01, 0x0a, 0x09,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x27, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x6c, 0x53, 0x69, 0x67, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x27,
	0x0a, 0x0c, 0x45, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0c, 0x45, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x78, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x45,
	0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x42, 0x0f, 0x0a, 0x0d,
	0x5f, 0x45, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x22, 0x21, 0x0a,
	0x09, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x22, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x1f, 0x0a, 0x07, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x61, 0x32, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufs_shared_proto_rawDescOnce sync.Once
	file_protobufs_shared_proto_rawDescData = file_protobufs_shared_proto_rawDesc
)

func file_protobufs_shared_proto_rawDescGZIP() []byte {
	file_protobufs_shared_proto_rawDescOnce.Do(func() {
		file_protobufs_shared_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_shared_proto_rawDescData)
	})
	return file_protobufs_shared_proto_rawDescData
}

var file_protobufs_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobufs_shared_proto_goTypes = []interface{}{
	(*IntType)(nil),    // 0: IntType
	(*LongType)(nil),   // 1: LongType
	(*FloatType)(nil),  // 2: FloatType
	(*IdentType)(nil),  // 3: IdentType
	(*StringType)(nil), // 4: StringType
	(*TagType)(nil),    // 5: TagType
}
var file_protobufs_shared_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobufs_shared_proto_init() }
func file_protobufs_shared_proto_init() {
	if File_protobufs_shared_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufs_shared_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_shared_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_shared_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_shared_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_shared_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_shared_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobufs_shared_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_shared_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobufs_shared_proto_goTypes,
		DependencyIndexes: file_protobufs_shared_proto_depIdxs,
		MessageInfos:      file_protobufs_shared_proto_msgTypes,
	}.Build()
	File_protobufs_shared_proto = out.File
	file_protobufs_shared_proto_rawDesc = nil
	file_protobufs_shared_proto_goTypes = nil
	file_protobufs_shared_proto_depIdxs = nil
}
